version: '3.3'
services:
  redisearch:
    image: redislabs/redisearch:latest
    container_name: redisearch
    ports:
      - 6379:6379
    volumes:
      - searchdata:/Users/juliejung/Desktop/redisearch/data
  web:
    build: ./search
    command: npm run search-dev
    depends_on:
      - redisearch
    ports:
      - 2000:2000
    volumes:
      - ./search:/searchService/
      - /searchService/node_modules
volumes:
  searchdata:
    driver: local
