version: '3'
services:
  mainserver:
    build: ./services/main
    container_name: mainserver
    ports:
      - 80:80
    volumes:
      - ./services/main:/mainServer/
      - /mainServer/node_modules
  redisearch:
    image: redislabs/redisearch:latest
    container_name: redisearch
    depends_on:
      - mainserver
    ports:
      - 6379:6379
    volumes:
      - searchdata:/Users/juliejung/Desktop/redisearch/data
  search:
    build: ./services/search
    container_name: searchservice
    command: npm run search-dev
    depends_on:
      - mainserver
      - redisearch
    ports:
      - 2000:2000
    volumes:
      - ./services/search:/searchService/
      - /searchService/node_modules
volumes:
  searchdata:
    driver: local
