version: '3'
services:
  mainserver:
    build: ./services/main/server
    # command: npm run start
    container_name: mainserver
    ports:
      - 80:80
    volumes:
      - ./services/main/server/:/usr/app
      - /usr/app/node_modules
  client:
    build:
      context: ./services/main/react-client
    command: npm start
    volumes:
      - ./services/main/react-client:/usr/app
      - /usr/app/node_modules
    depends_on:
      - mainserver
    ports:
      - 3000:3000
  redisearch:
    image: redislabs/redisearch:latest
    container_name: redisearch
    depends_on:
      - mainserver
    ports:
      - 6379:6379
    volumes:
      - searchdata:/Users/juliejung/Desktop/redisearch/data
  search:
    build: ./services/search
    container_name: searchservice
    command: npm run search-dev
    depends_on:
      - mainserver
      - redisearch
    ports:
      - 2000:2000
    volumes:
      - ./services/search:/searchService/
      - ./services/search/package.json:/searchService/package.json
      - /searchService/node_modules
volumes:
  searchdata:
    driver: local
