version: '3.3'
services:
  mainserver:
    build: ./server
    command: npm run server-dev
    container_name: mainserver
    ports:
      - 3000:3000
    volumes:
      - ./server:/mainServer/
      - /mainServer/node_modules
  redisearch:
    image: redislabs/redisearch:latest
    container_name: redisearch
    ports:
      - 6379:6379
    volumes:
      - searchdata:/Users/juliejung/Desktop/redisearch/data
  search:
    build: ./search
    command: npm run search-dev
    depends_on:
      - redisearch
      - mainserver
    ports:
      - 2000:2000
    volumes:
      - ./search:/searchService/
      - /searchService/node_modules
volumes:
  searchdata:
    driver: local
