version: '3.7'
services:
  mainserver:
    build: ./services/main
    # command: npm run start
    container_name: mainserver
    ports:
      - 3000:3000
    volumes:
      - ./services/main:/mainServer/
      - ./services/main/package.json:/mainServer/package.json
      - /mainServer/node_modules
  redisearch:
    image: redislabs/redisearch:latest
    container_name: redisearch
    depends_on:
      - mainserver
    ports:
      - 6379:6379
    volumes:
      - searchdata:/Users/juliejung/Desktop/redisearch/data
  search:
    build: ./services/search
    container_name: searchservice
    command: npm run search-dev
    depends_on:
      - mainserver
      - redisearch
    ports:
      - 2000:2000
    volumes:
      - ./services/search:/searchService/
      - ./services/search/package.json:/searchService/package.json
      - /searchService/node_modules
volumes:
  searchdata:
    driver: local
