version: '3.3'
services:
  mainserver:
    build: ./main
    command: bash -c "npm run server-dev && npm run build"
    container_name: mainserver
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./main:/mainServer/
      - /mainServer/node_modules
  redisearch:
    image: redislabs/redisearch:latest
    container_name: redisearch
    depends_on:
      - mainserver
    ports:
      - 6379:6379
    volumes:
      - searchdata:/Users/juliejung/Desktop/redisearch/data
  search:
    build: ./search
    command: npm run search-dev
    container_name: searchservice
    depends_on:
      - redisearch
    ports:
      - 2000:2000
    volumes:
      - ./search:/searchService/
      - /searchService/node_modules
volumes:
  searchdata:
    driver: local
